# Generated by Django 3.1.4 on 2020-12-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ViewSetApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeViewSetModel',
            new_name='EmployeeViewSet',
        ),
    ]
