# Generated by Django 3.1.4 on 2020-12-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ViewSetApp', '0002_auto_20201221_1128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeViewSet',
            new_name='Employee',
        ),
    ]
